

describe("Reports", () => {
  it("Homepage Tests", () => {
    const baseUrl = "https://membercentral.renaissanceins.com";
    // cy.login(`${baseUrl}`, "MMTestExt@MM.com","@MMRodeo22");
    cy.login(`${baseUrl}`, "MMTestExt@MM.com", "@MMRodeo22");
    const reportsUrl = `${baseUrl}/Reports`;
    cy.request(reportsUrl).then((response) => {
      cy.visit(reportsUrl);
    });
    cy.getIframe('#ReportsFrame').find("#grid > tbody > tr:nth-child(1) > td:nth-child(1)").should('have.length.greaterThan', 0);

    cy.get('#reportsMenu > li:nth-child(2) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#grid > tbody > tr:nth-child(1) > td:nth-child(1)").should('have.length.greaterThan', 0);
    cy.wait(30000);
    cy.get('#reportsMenu > li:nth-child(3) > span').click();
    cy.getIframe('#ReportsFrame').find("#grid > tbody > tr:nth-child(1) > td:nth-child(1)").should('have.length.greaterThan', 0);
    cy.get('#reportsMenu > li:nth-child(4) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#grid > tbody > tr:nth-child(1) > td:nth-child(1)").should('have.length.greaterThan', 0);
    cy.get('#reportsMenu > li:nth-child(5) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(8)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div:nth-child(3)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#grid > tbody > tr:nth-child(1) > td:nth-child(1)").should('have.length.greaterThan', 0);
    cy.get('#reportsMenu > li:nth-child(6) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(3) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-purple.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(3) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-skyblue.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(2) > div").should('have.length.greaterThan', 0);
    cy.get('#reportsMenu > li:nth-child(6) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(1) > div.text-block.font-size-medium.font-weight-default.color-black.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(3) > div.text-block.font-size-medium.font-weight-default.color-red.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(5) > div.text-block.font-size-medium.font-weight-default.color-black.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(7) > div.text-block.font-size-medium.font-weight-default.color-green.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(9) > div.text-block.font-size-medium.font-weight-default.color-black.spacing-none.horizontal-center").should('have.length.greaterThan', 0);
    cy.get('#reportsMenu > li:nth-child(6) > span').click();
    cy.wait(30000);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(2)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(7)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(7)").should('have.length.greaterThan', 0);
    cy.getIframe('#ReportsFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(7)").should('have.length.greaterThan', 0);
  });
});
