var expect = chai.expect;

var test;

describe("GrowthTrak", () => {
  it("Homepage Tests", () => {
    cy.clearCookies()
    const baseUrl = "https://membercentral.renaissanceins.com";
    // cy.login(`${baseUrl}`, "MMTestExt@MM.com","@MMRodeo22");
    cy.login(`${baseUrl}`, "MMTestExt@MM.com", "@MMRodeo22");
    const growthTrakUrl = `${baseUrl}/GrowthTrak`;
    cy.request(growthTrakUrl).then((response) => {
      cy.visit(growthTrakUrl);
    });
    cy.getIframe('#GrowthTrakFrame').find("#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div.text-block.font-size-large.font-weight-bold.color-purple.spacing-none.horizontal-center").should('have.length.greaterThan', 0)
    cy.get('#growthTrakMenu > li:nth-child(2) > span').click();
    cy.wait(30000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(4) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-skyblue.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.get('#growthTrakMenu > li:nth-child(3) > span').click();
    cy.wait(60000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(1) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(5)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(8)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(3) > div > widget > blox > div > div > div > div > div > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > div:nth-child(3)').should('have.length.greaterThan', 0);

    cy.get('#growthTrakMenu > li:nth-child(4) > span').click();
    cy.wait(60000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-grey.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(3) > div:nth-child(1) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-purple.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(3) > div:nth-child(2) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-skyblue.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    
    cy.get('#growthTrakMenu > li:nth-child(5) > span').click();
    cy.wait(30000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(4) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div > div').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(6) > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div > div:nth-child(1) > div.text-block.font-size-medium.font-weight-default.color-black.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
    cy.get('#growthTrakMenu > li:nth-child(6) > span').click();
    cy.wait(30000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div:nth-child(4)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(4)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(4)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(1) > div.text-block.font-size-default.font-weight-default.color-default.spacing-none.horizontal-left.condition_data.clickable-element').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(2) > div:nth-child(9)').should('have.length.greaterThan', 0);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div.dashboard-layout-cell.hide-resizers > div.dashboard-layout-subcell-host.showjustme-parent > div > widget > blox > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(9)').should('have.length.greaterThan', 0);
    cy.get('#growthTrakMenu > li:nth-child(7) > span').click();
    cy.wait(30000);
    cy.getIframe('#GrowthTrakFrame').find('#prism-mainview > div.prism-persistent-mainview-holder > div > div.collapsible-pane.errvil-warpper > div > dashboard > div > div.content > div > div:nth-child(1) > div > div > div:nth-child(2) > div:nth-child(4) > div > widget > blox > div > div > div > div > div > div.text-block.font-size-large.font-weight-bold.color-teal.spacing-none.horizontal-center').should('have.length.greaterThan', 0);
  });
});
